server:
  port: 9501

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:pch@eureka1:7001/eureka,http://admin:pch@eureka2:7002/eureka,http://admin:pch@eureka3:7003/eureka
    register-with-eureka: false

spring:
  application:
    name:  springcloud-zuul-gateway
