server:
  port: 7001
eureka:
  instance:  # eureka实例定义
    hostname: eureka1 # 定义 Eureka 实例所在的主机名称
    prefer-ip-address: false
  client:
    service-url:
      #将自己注册到eureka2和eureka3上
      defaultZone: http://admin:pch@eureka2:7002/eureka/,http://admin:pch@eureka3:7003/eureka/
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式，保护模式用于某个服务下线后断线重连时注册中心不会剔除它

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: pch